-- Rate Limiting Configuration for Self-Hosted Supabase
-- These are configured via environment variables in your Supabase stack

-- For Gotrue (Auth) rate limiting, add these to your Supabase configuration:

-- GOTRUE_RATE_LIMIT_EMAIL_SEND=5       -- Max 5 emails per minute
-- GOTRUE_RATE_LIMIT_TOKEN_REFRESH=10  -- Max 10 token refreshes per minute
-- GOTRUE_RATE_LIMIT_LOGIN=5           -- Max 5 login attempts per minute

-- Note: For self-hosted Supabase on Coolify, configure these in your
-- Supabase service's environment variables or in gotrue.yml

-- If you cannot configure Gotrue directly, you can add a database-level
-- rate limiting trigger as a fallback:

-- Create function to track login attempts
create table if not exists login_attempts (
  id bigint generated by default as identity primary key,
  email text not null,
  attempt_time timestamptz default now(),
  ip_address inet
);

-- Create index for faster lookups
create index if not exists idx_login_attempts_email_time
  on login_attempts(email, attempt_time);

-- Function to check and record login attempt
create or replace function check_login_rate_limit()
returns trigger as $$
declare
  attempts_count integer;
  window_start timestamptz := now() - interval '5 minutes';
begin
  -- Count attempts in last 5 minutes
  select count(*)
  into attempts_count
  from login_attempts
  where email = new.email
    and attempt_time > window_start;

  -- If more than 5 attempts, raise exception
  if attempts_count >= 5 then
    raise exception 'Too many login attempts. Please try again in 5 minutes.';
  end if;

  -- Record this attempt
  insert into login_attempts (email, ip_address)
  values (new.email, new.raw_ip::inet);

  return new;
end;
$$ language plpgsql security definer;

-- Apply rate limiting to login
-- Note: This requires Gotrue webhook integration
-- For now, the simplest solution is to configure rate limits in Gotrue
